### ISSUE TITLE
C# to GDScript

### ISSUE THREAD

**Issue by whtemple1959** [kiriri/gd2cs.py#10]
There is a certain plugin which it appears would be a benefit to my project, but unfortunately it is written in C# and I do not have that module implemented in my version of Godot. 
Frankly I am not interested in going to that level of hassle for one plugin.
It would be great to have companion application to convert C# code to GDScript to hopefully allow those type plugins to be modified to work in regular Godot.
Since you obviously have the skills you must be the person for the job.
Sleep on it
Thanks
Respectfully

**Comment by kiriri** [comment]
Sorry, this is out of scope for this project. I don't use Godot anymore. I don't earn money from this. And I don't have the free time to spare. I'm maintaining this project in its current state, and that's it. If someone else wants to implement this, I'd be happy to merge it into the project though.

**Comment by NickToony** [comment]
@whtemple1959 Are you referring to my gd-retroterrain project you recently forked? I was considering converting it to GDScript anyway to make easier to use.

**Comment by whtemple1959** [comment]
yes I am speaking of your project. ease let me know when your update is available.As I am very new to C++, Godot, and development I am struggling with many issues, mainly getting my heigthmap to work but I hope to be utilizing your project or something similar to achieve the look I am seeking
by the way how did you manage to pick my comment to reference?
