### ISSUE TITLE
Add support for a `while` loop

### ISSUE THREAD

**Issue by cgbeutler** [kiriri/gd2cs.py#3]
It appears the `while` loops are not converted by the tool.

Example input:
```coffeescript
	#remove invalid values from arr
	var i = 0
	while i < len(arr):
		if not arr[i].is_valid():
			arr.remove( i )
		else:
			i += 1
```

The tool leaves the while loop alone. Everything else seems to work fine around/in it.

**Comment by kiriri** [comment]
Thank you for submitting these issues.  I'm sure they affected a lot of people. I never used static functions, so I would have never noticed that myself. The while loop on the other hand I just presumed I had implemented alongside the other loops, and never tested :sweat_smile:

**Comment by cgbeutler** [comment]
Yeah, I tend to use/abuse a lot of fringe stuff. Not sure what's best to focus on. The tool does save a good amount of time as-is, though.

**Comment by kiriri** [comment]
> The tool does save a good amount of time as-is, though.
That is very uplifting to hear!
